// <auto-generated />
using System;
using CargoExpress.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CargoExpress.Migrations
{
    [DbContext(typeof(CargoContext))]
    [Migration("20260520140539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CargoExpress.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CargoExpress.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Минимальный тариф в черте города",
                            PriceValue = 500m,
                            Route = "По городу (до 50 км)",
                            Unit = "руб/выезд"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Сверх нормы — доплата за километр",
                            PriceValue = 25m,
                            Route = "По городу (более 50 км)",
                            Unit = "руб/км"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Доставка в соседние регионы",
                            PriceValue = 30m,
                            Route = "Межгород (100–500 км)",
                            Unit = "руб/км"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Дальние рейсы — цена ниже",
                            PriceValue = 25m,
                            Route = "Межгород (500–1500 км)",
                            Unit = "руб/км"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Бригада 2 грузчика + машина, смена 8 ч",
                            PriceValue = 3000m,
                            Route = "Квартирный переезд",
                            Unit = "руб/смена"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Бригада 4 грузчика + крупный транспорт",
                            PriceValue = 5000m,
                            Route = "Офисный переезд",
                            Unit = "руб/смена"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Наём грузчиков на почасовой основе",
                            PriceValue = 500m,
                            Route = "Грузчики (без авто)",
                            Unit = "руб/ч"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Упаковочные материалы и работа",
                            PriceValue = 200m,
                            Route = "Упаковка вещей",
                            Unit = "руб/коробка"
                        });
                });

            modelBuilder.Entity("CargoExpress.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 500m,
                            Description = "Быстрая доставка в черте города на любом расстоянии",
                            Details = "Перевозим мебель, технику, стройматериалы. Грузчики в наличии. Работаем 7 дней в неделю с 8:00 до 22:00.",
                            Icon = "🏙️",
                            Name = "Грузоперевозки по городу"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 25m,
                            Description = "Надёжная доставка между городами России",
                            Details = "Доставляем грузы по всей России. Страхование груза. GPS-отслеживание. Срок доставки от 1 дня.",
                            Icon = "🛣️",
                            Name = "Межгород"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 3000m,
                            Description = "Полный цикл переезда с упаковкой и разборкой мебели",
                            Details = "Бригада грузчиков, упаковочные материалы, разборка и сборка мебели. Страховка имущества включена.",
                            Icon = "🏠",
                            Name = "Квартирный переезд"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 5000m,
                            Description = "Перевозка офиса без простоев — в выходные или ночью",
                            Details = "Разберём, упакуем, перевезём и соберём всё оборудование. Работаем ночью и в выходные для минимального простоя бизнеса.",
                            Icon = "🏢",
                            Name = "Офисный переезд"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 800m,
                            Description = "Небольшой объём вещей — быстро и недорого",
                            Details = "Перевезём сумки, коробки, бытовую технику. Газель или минивэн. Идеально для студентов и небольших переездов.",
                            Icon = "📦",
                            Name = "Перевозка вещей"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 1500m,
                            Description = "Перевозка кирпича, плитки, цемента, стекла",
                            Details = "Специализированные автомобили для стройматериалов. Манипулятор для тяжёлых грузов. Доставка на объект.",
                            Icon = "🧱",
                            Name = "Доставка стройматериалов"
                        });
                });

            modelBuilder.Entity("CargoExpress.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerKm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            Icon = "🚐",
                            IsAvailable = true,
                            Model = "ГАЗ-3302",
                            Name = "Газель",
                            PricePerKm = 25m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 3,
                            Icon = "🚐",
                            IsAvailable = true,
                            Model = "ГАЗ-А21R22",
                            Name = "Газель Некст",
                            PricePerKm = 30m
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 20,
                            Icon = "🚛",
                            IsAvailable = false,
                            Model = "MAN TGX 18.440",
                            Name = "Фура",
                            PricePerKm = 80m
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 8,
                            Icon = "🚚",
                            IsAvailable = true,
                            Model = "КАМАЗ-4308",
                            Name = "Среднетоннажник",
                            PricePerKm = 50m
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 5,
                            Icon = "❄️",
                            IsAvailable = true,
                            Model = "Mercedes Atego",
                            Name = "Рефрижератор",
                            PricePerKm = 45m
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 10,
                            Icon = "🏗️",
                            IsAvailable = false,
                            Model = "Урал-4320",
                            Name = "Манипулятор",
                            PricePerKm = 65m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
